// AI Destination Guide Generator Service for OASIS India Thrissur
// Automatically generates 50km radius nearby tourist attraction guides, 1-day itineraries,
// maps, weather, opening hours, entry fees, activities & photography spots for ANY location name.

export const AI_DESTINATION_DATABASE = {
  'kochi': {
    locationName: 'Kochi (Cochin)',
    tagline: 'Queen of the Arabian Sea & Historic Heritage Harbor',
    heroImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1920&q=85',
    nearestStation: 'Ernakulam Junction (ERS) / Ernakulam Town (ERN) – 5 km',
    nearestAirport: 'Cochin International Airport (COK) – Nedumbassery – 28 km',
    bestTime: 'September to March (Pleasant Coastal Breeze & Festive Season)',
    weather: '28°C • Warm & Tropical Breeze • Humidity 75%',
    googleMapCoordinates: '9.9312° N, 76.2673° E',
    googleMapLink: 'https://maps.google.com/?q=Kochi',
    attractions: [
      {
        id: 'kochi-chinese-nets',
        name: 'Fort Kochi Chinese Fishing Nets (Cheena Vala)',
        distance: '12 km from Ernakulam South',
        travelTime: '25 mins drive / Ferry',
        image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Introduced by 14th-century Chinese explorer Zheng He, these cantilevered mechanical fishing nets line the Fort Kochi beach. Sunset views with fishing silhouettes are one of India\'s most photographed sights.',
        highlights: ['14th-century cantilevered fishing mechanism', 'Iconic sunset silhouette photography', 'Live seafood stalls along promenade'],
        activities: ['Fishing Demonstration', 'Sunset Photography', 'Seafood Tasting', 'Beach Walk'],
        openingHours: '24 Hours Open (Best 05:30 PM Sunset)',
        entryFee: 'Free Entry (Fishermen Tip for Net Pulling ₹50)',
        bestPhotoSpot: 'Vasco da Gama Square Promenade at 06:15 PM sunset',
        mapLink: 'https://maps.google.com/?q=Chinese+Fishing+Nets+Kochi'
      },
      {
        id: 'kochi-dutch-palace',
        name: 'Mattancherry Dutch Palace & Ancient Ramayana Murals',
        distance: '10 km from Ernakulam Center',
        travelTime: '20 mins drive',
        image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Built by the Portuguese in 1555 and gifted to the Raja of Kochi, then renovated by the Dutch in 1663. Houses life-sized portraits of Cochin Maharajas and 300-year-old Hindu mythological tempera murals.',
        highlights: ['16th-century royal coronation hall', 'World-renowned Ramayana wall murals', 'Royal palanquins & coronation costumes'],
        activities: ['Heritage Walk', 'Mural Art Study', 'Museum Tour'],
        openingHours: '09:45 AM – 04:45 PM (Closed Fridays)',
        entryFee: '₹10 Adults',
        bestPhotoSpot: 'Courtyard Gateway & Central Kerala architecture arch',
        mapLink: 'https://maps.google.com/?q=Mattancherry+Palace'
      },
      {
        id: 'kochi-jew-town',
        name: 'Paradesi Jewish Synagogue & Jew Town Antique Street',
        distance: '10.5 km from Ernakulam',
        travelTime: '22 mins drive',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Constructed in 1568 by Malabar Yehudan (Cochin Jewish community), it is the oldest active synagogue in the Commonwealth. Features hand-painted 18th-century blue willow porcelain floor tiles from Canton, Belgian crystal chandeliers, and ancient Hebrew Torah scrolls.',
        highlights: ['Hand-painted 18th-century Canton porcelain floor', 'Belgian crystal chandeliers & gold crowns', 'Famous Jew Town spice & antique alley'],
        activities: ['Synagogue Tour', 'Antique & Spice Shopping', 'Heritage Cafe Dining'],
        openingHours: '10:00 AM – 05:00 PM (Closed Saturdays & Jewish Holidays)',
        entryFee: '₹10 Entry',
        bestPhotoSpot: 'Jew Town Clock Tower & Cobblestone Antique Lane',
        mapLink: 'https://maps.google.com/?q=Paradesi+Synagogue'
      },
      {
        id: 'kochi-marine-drive',
        name: 'Marine Drive Waterfront Promenade & Rainbow Bridge',
        distance: '2 km from Ernakulam Junction',
        travelTime: '5 mins drive',
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'A 3-kilometer scenic pedestrian boulevard overlooking the Vembanad backwaters and Kochi shipping harbor. Offers sunset harbor cruises, speedboating to Bolgatty, and views of the Chinese fishing nets.',
        highlights: ['Iconic curved Rainbow & Chinese Net Bridges', 'Harbor backwater sunset cruise boats', 'Night illumination skyline'],
        activities: ['Evening Promenade Walk', '1-Hour Harbor Cruise', 'Street Food & Tea Stalls'],
        openingHours: '24 Hours Open (Cruise 09:00 AM – 08:30 PM)',
        entryFee: 'Free Walk / Harbor Cruise ₹150 – ₹300',
        bestPhotoSpot: 'Rainbow Bridge arch facing sunset over Bolgatty Island',
        mapLink: 'https://maps.google.com/?q=Marine+Drive+Kochi'
      },
      {
        id: 'kochi-st-francis',
        name: 'St. Francis CSI Church (Vasco da Gama’s 1503 Burial Church)',
        distance: '12.5 km from Ernakulam',
        travelTime: '28 mins drive',
        image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Constructed in 1503 by Portuguese Franciscan friars, this is the oldest European church built in India. Portuguese explorer Vasco da Gama was buried here in 1524 before his remains were relocated to Lisbon.',
        highlights: ['Oldest European church in India (1503)', 'Vasco da Gama original burial vault', 'Colonial Portuguese gabled timber facade'],
        activities: ['Historical Sightseeing', 'Architecture Tour', 'Quiet Prayer'],
        openingHours: '07:00 AM – 06:30 PM (Sundays 08:30 AM – 06:30 PM)',
        entryFee: 'Free Entry',
        bestPhotoSpot: 'Gable Arch Facade with rain tree shadow',
        mapLink: 'https://maps.google.com/?q=St+Francis+Church+Kochi'
      },
      {
        id: 'kochi-santa-cruz',
        name: 'Santa Cruz Cathedral Basilica Fort Kochi',
        distance: '13 km from Ernakulam',
        travelTime: '30 mins drive',
        image: 'https://images.unsplash.com/photo-1548625361-16eb16262438?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'One of the eight basilicas in India, built originally by Portuguese Viceroy Francesco de Almeida in 1505. Elevated to cathedral status by Pope Paul IV in 1558, featuring grand Gothic white spires and Italian painted ceilings.',
        highlights: ['Gothic whitewashed dual spires', 'Intricate Italian fresco paintings of Last Supper', 'Historic 500-year-old heritage monument'],
        activities: ['Basilica Tour', 'Spiritual Contemplation', 'Gothic Photography'],
        openingHours: '07:00 AM – 06:30 PM (Daily)',
        entryFee: 'Free Entry',
        bestPhotoSpot: 'Dual Spire Frontage from Fort Kochi Bastion Street',
        mapLink: 'https://maps.google.com/?q=Santa+Cruz+Basilica+Kochi'
      },
      {
        id: 'kochi-hill-palace',
        name: 'Hill Palace Museum Tripunithura (Seat of Cochin Maharajas)',
        distance: '14 km from Ernakulam Junction',
        travelTime: '30 mins drive',
        image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Spread across 54 acres with 49 traditional Kerala-style buildings built in 1865. The official administrative seat of the Kingdom of Cochin, housing the gold crown of the Maharaja, throne, weapon gallery, and deer park.',
        highlights: ['Largest archaeological museum in Kerala', 'Maharaja’s 1.75 kg solid gold crown & royal throne', '54-acre deer park & heritage botanical garden'],
        activities: ['Royal Artifact Tour', 'Heritage Walk', 'Deer Park Stroll'],
        openingHours: '09:30 AM – 04:30 PM (Closed Mondays)',
        entryFee: '₹30 Adults, ₹10 Children',
        bestPhotoSpot: 'Imperial Gateway Lawn framing main Palace staircase',
        mapLink: 'https://maps.google.com/?q=Hill+Palace+Tripunithura'
      },
      {
        id: 'kochi-cherai-beach',
        name: 'Cherai Beach & Vypin Island Coastal Sands',
        distance: '25 km from Ernakulam (via Goshree Bridges)',
        travelTime: '45 mins drive',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'A 10-kilometer golden sand beach where backwaters and the Arabian Sea meet side by side. Known for shallow calm waters ideal for swimming, dolphin sightings, and seaside fresh seafood shacks.',
        highlights: ['10 km clean golden sand shoreline', 'Rare meeting point of backwaters & Arabian Sea', 'Playful dolphin sightings near breakwaters'],
        activities: ['Beach Swimming', 'Speedboating & Jet Ski', 'Sunset Walks', 'Tender Coconut Sipping'],
        openingHours: '24 Hours Open (Lifeguard 06:00 AM – 06:30 PM)',
        entryFee: 'Free Entry',
        bestPhotoSpot: 'Cherai Beach North Pier facing sunset waves',
        mapLink: 'https://maps.google.com/?q=Cherai+Beach'
      }
    ],
    oneDayItinerary: [
      { time: '08:30 AM', title: 'Start & Heritage Walk', place: 'Fort Kochi St. Francis & Santa Cruz', desc: 'Explore India’s oldest European church (1503) and Gothic basilica spires.' },
      { time: '10:30 AM', title: 'Attraction 1: Royal Heritage', place: 'Mattancherry Dutch Palace', desc: 'Admire ancient 300-year-old Ramayana murals and Maharaja coronation regalia.' },
      { time: '11:45 AM', title: 'Attraction 2: Jewish Heritage', place: 'Jew Town & Paradesi Synagogue', desc: 'Walk historic cobblestone streets, shop aromatic spices and view 18th-century Canton porcelain floor tiles.' },
      { time: '01:15 PM', title: 'Lunch Break', place: 'Fort Kochi Waterfront Cafe', desc: 'Savor authentic Malabar Fish Curry, appam, and Kerala seafood thali.' },
      { time: '02:45 PM', title: 'Attraction 3: Royal Seat', place: 'Hill Palace Tripunithura', desc: 'Marvel at the 1.75kg solid gold crown of Cochin Kingdom in a 54-acre palace complex.' },
      { time: '05:15 PM', title: 'Attraction 4: Sunset Spectacle', place: 'Chinese Fishing Nets Promenade', desc: 'Watch mechanical cantilevered Chinese fishing nets dip into water against glorious sunset sky.' },
      { time: '07:00 PM', title: 'Harbor Cruise & Dinner', place: 'Marine Drive Rainbow Bridge', desc: 'Enjoy relaxing 1-hour backwater harbor cruise witnessing illuminated city skyline.' }
    ]
  },
  'kollam': {
    locationName: 'Kollam (Quilon)',
    tagline: 'Ashtamudi Backwaters, Jatayu Rock & Coastal Heritage Port',
    heroImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1920&q=85',
    nearestStation: 'Kollam Junction (QLN) – 0 km (Gateway to Kerala Backwaters)',
    nearestAirport: 'Trivandrum International Airport (TRV) – 71 km / Cochin Airport (COK) – 150 km',
    bestTime: 'September to March (Pleasant Backwater Breeze)',
    weather: '29°C • Warm Coastal & Backwater Breeze • Humidity 72%',
    googleMapCoordinates: '8.8932° N, 76.6141° E',
    googleMapLink: 'https://maps.google.com/?q=Kollam',
    attractions: [
      {
        id: 'kollam-ashtamudi-lake',
        name: 'Ashtamudi Lake & Backwater Houseboat Cruise',
        distance: '2 km from Kollam Junction',
        travelTime: '8 mins drive',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'The "Gateway to the Backwaters" — Ashtamudi is an 8-arm palm-shaped wetland spanning 61 km². Luxury houseboats cruise from Kollam to Alappuzha through lush coconut groves, Chinese fishing nets, and bird-filled canals.',
        highlights: ['61 km² palm-shaped backwater wetland', 'Luxury houseboat cruise to Alappuzha', 'Kollam Boat Race in September'],
        activities: ['Houseboat Cruise', 'Backwater Birdwatching', 'Fishing Village Visits', 'Canal Photography'],
        openingHours: 'Cruises 08:00 AM – 06:00 PM (Overnight Option)',
        entryFee: 'Cruise ₹1,500 – ₹12,000',
        bestPhotoSpot: 'Kollam Boat Jetty at golden hour with palm reflections',
        mapLink: 'https://maps.google.com/?q=Ashtamudi+Lake'
      },
      {
        id: 'kollam-jatayu-rock',
        name: 'Jatayu Earth\'s Center (Chadayamangalam Rock)',
        distance: '38 km from Kollam (via MC Road)',
        travelTime: '55 mins drive',
        image: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'The world\'s largest bird sculpture — a 200-ft long, 15,000-ton concrete Jatayu set atop Chadayamangalam Rock. Features India\'s largest cable car ride, 6D theatre, trekking trails, and panoramic valley views.',
        highlights: ['World\'s largest bird sculpture (200 ft)', 'India\'s largest cable car ride', '6D adventure theatre & trekking'],
        activities: ['Cable Car Ride', 'Sculpture Viewing', 'Trekking', 'Adventure Park'],
        openingHours: '09:00 AM – 06:00 PM (Daily)',
        entryFee: '₹500 Adults, ₹350 Children (Cable Car & Park)',
        bestPhotoSpot: 'Jatayu Viewpoint Deck facing the valley at sunset',
        mapLink: 'https://maps.google.com/?q=Jatayu+Earth%27s+Center'
      },
      {
        id: 'kollam-thangassery-lighthouse',
        name: 'Thangassery Light House & British Fort',
        distance: '5 km from Kollam Junction',
        travelTime: '15 mins drive',
        image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Built in 1902 by the British, this 144-ft tall red-and-white lighthouse stands near the ruins of the 16th-century Thangassery (St. Thomas) Fort. Climb 193 spiral steps for a breathtaking Arabian Sea panorama.',
        highlights: ['144-ft British-era lighthouse (1902)', '16th-century Portuguese-Dutch fort ruins', '193-step spiral climb & sea panorama'],
        activities: ['Lighthouse Climb', 'Fort Ruin Walk', 'Sunset Photography', 'Beach Stroll'],
        openingHours: '10:00 AM – 05:00 PM (Monday Closed)',
        entryFee: '₹20 Adults, ₹10 Children',
        bestPhotoSpot: 'Lighthouse Base framing the fort cannon against sunset sea',
        mapLink: 'https://maps.google.com/?q=Thangassery+Light+House'
      },
      {
        id: 'kollam-munroe-island',
        name: 'Munroe Island (Munroethuruth) Hidden Lagoon',
        distance: '26 km from Kollam Junction',
        travelTime: '45 mins drive + Canoe Ride',
        image: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'A deltaic island network formed by the confluence of Kallada River and Ashtamudi Lake. Glide through narrow tree-canopied canals by country canoe, past toddy-shop villages and coir-making hamlets.',
        highlights: ['Confluence of Kallada River & Ashtamudi Lake', 'Narrow tree-canopied canoe canals', 'Traditional coir & toddy village life'],
        activities: ['Canoe Rides', 'Village Walks', 'Backwater Birding', 'Local Toddy Tasting'],
        openingHours: '08:00 AM – 05:00 PM (Daily)',
        entryFee: 'Canoe Ride ₹300 – ₹500',
        bestPhotoSpot: 'Coconut Canopy Canal Tunnel at noon sunbeams',
        mapLink: 'https://maps.google.com/?q=Munroe+Island'
      },
      {
        id: 'kollam-sasthamkotta-lake',
        name: 'Sasthamkotta Freshwater Lake',
        distance: '29 km from Kollam Junction',
        travelTime: '45 mins drive',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'The largest freshwater lake in Kerala (375 ha) and the drinking-water lifeline of the district. Ringed by green hills, it hosts the Sasthamkotta Sree Dharma Sastha temple on its bank.',
        highlights: ['Largest freshwater lake in Kerala', 'Hillside temple on the lake bank', 'Rare freshwater species sanctuary'],
        activities: ['Lakeside Walks', 'Temple Darshan', 'Birdwatching', 'Boating'],
        openingHours: '06:00 AM – 06:00 PM (Daily)',
        entryFee: 'Free Entry (Boating ₹100)',
        bestPhotoSpot: 'Western Ridge Hilltop framing the entire lake',
        mapLink: 'https://maps.google.com/?q=Sasthamkotta+Lake'
      },
      {
        id: 'kollam-thenmala',
        name: 'Thenmala Dam & Ecotourism Boardwalk',
        distance: '66 km from Kollam Junction',
        travelTime: '1 hr 30 mins drive',
        image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'India\'s first planned ecotourism destination. Walk the treetop boardwalk above the Kallada reservoir, hike the Leisure Trail, and experience the butterfly safari and adventure zone.',
        highlights: ['India\'s first planned ecotourism spot', 'Treetop boardwalk over Kallada reservoir', 'Butterfly safari & adventure zone'],
        activities: ['Treetop Walk', 'Nature Trails', 'Boating', 'Adventure Rides'],
        openingHours: '09:00 AM – 05:00 PM (Daily)',
        entryFee: '₹50 Entry + Boardwalk ₹200',
        bestPhotoSpot: 'Boardwalk arch overlooking the reservoir islands',
        mapLink: 'https://maps.google.com/?q=Thenmala+Ecotourism'
      },
      {
        id: 'kollam-beach',
        name: 'Kollam Beach & Mahatma Gandhi Park',
        distance: '2.5 km from Kollam Junction',
        travelTime: '8 mins drive',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'A serene stretch of Arabian Sea coast beside the old port. The Mahatma Gandhi Park offers lush lawns, fountains, and a watchtower overlooking the Ashtamudi channel mouth.',
        highlights: ['Golden Arabian Sea shoreline', 'Mahatma Gandhi Park lawns & fountain', 'Watchtower with channel views'],
        activities: ['Beach Walks', 'Sunset Watching', 'Park Picnics', 'Street Food'],
        openingHours: '24 Hours (Park 06:00 AM – 08:00 PM)',
        entryFee: 'Free Entry',
        bestPhotoSpot: 'MG Park Watchtower at sunset',
        mapLink: 'https://maps.google.com/?q=Kollam+Beach'
      },
      {
        id: 'kollam-paravur-lake',
        name: 'Paravur Lake & Puthenkavu Backwater Village',
        distance: '25 km from Kollam Junction',
        travelTime: '40 mins drive',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'A calm 6.4 km² estuary where the sea meets the backwaters. Spot migratory birds on white-sand islands, enjoy canoe rides, and walk the Puthenkavu backwater village boardwalks.',
        highlights: ['6.4 km² sea-backwater estuary', 'Migratory bird white-sand islands', 'Puthenkavu village boardwalk'],
        activities: ['Canoe Rides', 'Birdwatching', 'Village Walk', 'Sunset Cruise'],
        openingHours: '07:00 AM – 06:00 PM (Daily)',
        entryFee: 'Free (Canoe ₹250)',
        bestPhotoSpot: 'Puthenkavu Boardwalk facing the estuary bridge',
        mapLink: 'https://maps.google.com/?q=Paravur+Lake'
      }
    ],
    oneDayItinerary: [
      { time: '08:30 AM', title: 'Start & Royal Port', place: 'Kollam Junction to Boat Jetty', desc: 'Begin at the historic port town and board your Ashtamudi backwater cruise.' },
      { time: '10:30 AM', title: 'Attraction 1: Backwater Cruise', place: 'Ashtamudi Lake Houseboat', desc: 'Glide through palm-fringed canals past coir villages and fishing nets.' },
      { time: '12:30 PM', title: 'Lunch Break', place: 'Backwater Houseboat Kitchen', desc: 'Authentic Kerala seafood sadya served on board.' },
      { time: '02:00 PM', title: 'Attraction 2: Coastal Heritage', place: 'Thangassery Light House & Fort', desc: 'Climb 193 spiral steps for the Arabian Sea panorama and explore fort ruins.' },
      { time: '04:30 PM', title: 'Attraction 3: Hidden Lagoon', place: 'Munroe Island Canoe', desc: 'Canoe through tree-canopied canals to the Kallada-Ashtamudi confluence.' },
      { time: '06:30 PM', title: 'Sunset & Departure', place: 'Kollam Beach & MG Park', desc: 'Watch golden sunset over the Arabian Sea from the MG Park watchtower.' }
    ]
  },
  'kodaikanal': {
    locationName: 'Kodaikanal',
    tagline: 'The Princess of Hill Stations',
    heroImage: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1920&q=85',
    nearestStation: 'Kodai Road Railway Station (KZN) – 80 km',
    nearestAirport: 'Madurai International Airport (IXM) – 120 km / Cochin International Airport (COK) – 260 km',
    bestTime: 'October to June (Spring & Summer)',
    weather: '18°C • Pleasant & Misty • Humidity 65%',
    googleMapCoordinates: '10.2381° N, 77.4892° E',
    googleMapLink: 'https://maps.google.com/?q=Kodaikanal',
    attractions: [
      {
        id: 'kodai-lake',
        name: 'Kodaikanal Star-Shaped Lake & Boating',
        distance: '1.2 km from Kodaikanal Bus Stand',
        travelTime: '5 mins drive',
        image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Constructed in 1863 by Sir Vere Henry Levinge, this iconic 60-acre star-shaped artificial lake is surrounded by lush Palani Hills. Visitors can enjoy luxury pedal boating, row boating, tandem cycling around the 5 km perimeter, and horse riding along the banks.',
        highlights: ['Iconic 60-acre star shape', 'Luxury pedal & row boating', '5 km cycling lake road loop'],
        activities: ['Pedal Boating', 'Row Boating', 'Perimeter Cycling', 'Horse Riding', 'Street Shopping'],
        openingHours: '06:00 AM – 05:30 PM (Daily)',
        entryFee: 'Free Entry (Boating ₹240 – ₹450)',
        bestPhotoSpot: 'Boat House Pier & Western Promenade at 7:30 AM mist rise',
        mapLink: 'https://maps.google.com/?q=Kodaikanal+Lake'
      },
      {
        id: 'bryant-park',
        name: 'Bryant Botanical Park & Glasshouse',
        distance: '1.5 km from Kodaikanal Center',
        travelTime: '6 mins drive',
        image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'A meticulously landscaped 20.5-acre botanical garden planned in 1908 by British forest officer H.D. Bryant. Features over 740 varieties of roses, exotic dahlias, Bodhi tree, and an ornate glasshouse hosting the annual May Flower Show.',
        highlights: ['740+ rose cultivars & glasshouse', '170-year-old Eucalyptus tree', 'Annual May Flower Show venue'],
        activities: ['Botanical Strolls', 'Floral Photography', 'Lawn Picnicking', 'Glasshouse Tour'],
        openingHours: '09:00 AM – 06:00 PM (Daily)',
        entryFee: '₹30 Adults, ₹15 Children, ₹50 Camera',
        bestPhotoSpot: 'Central Rose Arbours & Ornate Glasshouse Front Lawn',
        mapLink: 'https://maps.google.com/?q=Bryant+Park+Kodaikanal'
      },
      {
        id: 'coakers-walk',
        name: 'Coaker\'s Walk Valley Viewpoint',
        distance: '1.8 km from Kodaikanal Bus Stand',
        travelTime: '7 mins drive',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Constructed by Lt. Coaker in 1872, this 1-kilometer paved pedestrian path winds along the steep southern slopes of Kodai hill. Offers breathtaking 180-degree panoramic views of Madurai plains, Dolphin\'s Nose, and the rare Brockend Spectre cloud phenomenon.',
        highlights: ['1 km paved cliffside promenade', '180-degree Madurai valley vista', 'Telescope House observation tower'],
        activities: ['Morning Cliff Walks', 'Telescope Sightseeing', 'Cloud Photography', 'Cycling'],
        openingHours: '07:00 AM – 07:00 PM (Daily)',
        entryFee: '₹30 Entry, ₹20 Telescope View',
        bestPhotoSpot: 'Telescope House Pavilion overlooking Dolphin\'s Nose valley',
        mapLink: 'https://maps.google.com/?q=Coakers+Walk+Kodaikanal'
      },
      {
        id: 'green-valley-view',
        name: 'Green Valley View (Suicide Point)',
        distance: '5.5 km from Kodaikanal Lake',
        travelTime: '15 mins drive',
        image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Commanding a dramatic 5,000-foot drop into the dense Vaigai Dam valley, Green Valley View offers unforgettable sights of mist-clad mountain ridges and sprawling evergreen forests.',
        highlights: ['5,000 ft vertical valley drop', 'View of Vaigai Dam reservoir', 'Handicraft market street'],
        activities: ['Valley Sightseeing', 'Handicraft Shopping', 'Monkey Watching', 'Local Snacks Tasting'],
        openingHours: '07:00 AM – 06:00 PM (Daily)',
        entryFee: 'Free Entry',
        bestPhotoSpot: 'Guarded Lookout Balcony framing Vaigai Reservoir',
        mapLink: 'https://maps.google.com/?q=Green+Valley+View+Kodaikanal'
      },
      {
        id: 'pillar-rocks',
        name: 'Pillar Rocks Vertical Granite Cliffs',
        distance: '7.2 km from Kodaikanal Center',
        travelTime: '20 mins drive',
        image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Three massive vertical granite cliff formations standing 400 feet tall amidst mist and pine forests. Managed by the Tamil Nadu Forest Department, the manicured gardens in front provide awe-inspiring views of the chasm.',
        highlights: ['Three 400 ft sheer granite spires', 'Gasket Chasm valley views', 'Lush Forest Department garden'],
        activities: ['Cliff Sightseeing', 'Garden Relaxation', 'Landscape Photography', 'Souvenir Shopping'],
        openingHours: '09:00 AM – 04:30 PM (Daily)',
        entryFee: '₹10 Entry, ₹20 Camera',
        bestPhotoSpot: 'Garden Terrace framing the 3 Granite Pillars with fog',
        mapLink: 'https://maps.google.com/?q=Pillar+Rocks+Kodaikanal'
      },
      {
        id: 'guna-caves',
        name: 'Guna Caves (Devil\'s Kitchen)',
        distance: '8.5 km from Kodaikanal Center',
        travelTime: '22 mins drive',
        image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Famed by Kamal Haasan\'s hit movie "Gunaa" and the blockbuster film "Manjummel Boys", these deep natural rock caverns are nestled between Pillar Rocks. Surrounded by ancient tangled pine roots and shrouded in mystery.',
        highlights: ['Famed Manjummel Boys filming location', 'Intricate gnarled pine root forest', 'Deep natural mountain rock fissures'],
        activities: ['Root Forest Walks', 'Cinema Sightseeing', 'Photography', 'Nature Trails'],
        openingHours: '09:00 AM – 04:30 PM (Daily)',
        entryFee: '₹10 Entry',
        bestPhotoSpot: 'Ancient Gnarled Pine Root Canopy near Cave Entrance',
        mapLink: 'https://maps.google.com/?q=Guna+Caves+Kodaikanal'
      },
      {
        id: 'pine-forest',
        name: 'Kodaikanal Dense Pine Tree Forest',
        distance: '9.0 km from Kodaikanal Lake',
        travelTime: '24 mins drive',
        image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Planted by Mr. Bryant in 1906 to cultivate timber, this magnificent pine forest features tall, straight pine trunks stretching into the sky. Light rays filtering through mist create a dreamy atmosphere for movies and weddings.',
        highlights: ['Century-old towering pine plantation', 'Sunbeam atmospheric light rays', 'Iconic Kollywood filming spot'],
        activities: ['Horse Riding', 'Forest Photography', 'Cinematic Strolls', 'Pine Cone Collecting'],
        openingHours: '08:00 AM – 06:00 PM (Daily)',
        entryFee: 'Free Entry',
        bestPhotoSpot: 'Central Pine Corridor looking up into the canopy',
        mapLink: 'https://maps.google.com/?q=Pine+Forest+Kodaikanal'
      },
      {
        id: 'moir-point',
        name: 'Moir Point Valley Viewpoint',
        distance: '10.0 km from Kodaikanal Center',
        travelTime: '25 mins drive',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Named after Sir Thomas Moir who laid the monument stone in 1929 for the Goschen Road. Serves as the key gateway junction to Berijam Lake and offers sweeping vistas of the Palani range.',
        highlights: ['Historical 1929 Goschen Road monument', 'Berijam forest check-post gateway', 'Panoramic valley lookout'],
        activities: ['Monuments Viewing', 'Valley Sightseeing', 'Coffee Tasting', 'Forest Photography'],
        openingHours: '06:00 AM – 05:00 PM (Daily)',
        entryFee: '₹10 Entry',
        bestPhotoSpot: 'Stone Obelisk Lookout overlooking the valley',
        mapLink: 'https://maps.google.com/?q=Moir+Point+Kodaikanal'
      },
      {
        id: 'silver-cascade-falls',
        name: 'Silver Cascade 180-ft Waterfalls',
        distance: '8.0 km from Kodaikanal Bus Stand (on Laws Ghat Road)',
        travelTime: '20 mins drive',
        image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Formed by the overflow of Kodaikanal Lake, this magnificent 180-foot waterfall cascades down sheer rocks along the main Ghat Road entrance. A welcoming landmark for travelers arriving in Kodaikanal.',
        highlights: ['180 ft roaring waterfall', 'Main entrance landmark', 'Local spice & fruit stalls'],
        activities: ['Waterfall Viewing', 'Local Fruit Tasting', 'Roadside Photography'],
        openingHours: '24 Hours Open (Best 08:00 AM – 05:00 PM)',
        entryFee: 'Free Entry',
        bestPhotoSpot: 'Bridge Balcony facing the cascading main drop',
        mapLink: 'https://maps.google.com/?q=Silver+Cascade+Falls+Kodaikanal'
      },
      {
        id: 'dolphins-nose',
        name: 'Dolphin\'s Nose & Echo Rock Cliff',
        distance: '8.0 km from Kodaikanal Town (Vattakanal)',
        travelTime: '30 mins drive + 1 km trek',
        image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'A flat, protruding rock formation jutting out over a 6,600-foot deep abyss. The 1 km forest trail down through Vattakanal offers thrilling adventure, mountain views, and the nearby Echo Rock.',
        highlights: ['Protruding rock cliff over 6,600 ft abyss', 'Vattakanal village forest trail', 'Echo Rock extension viewpoint'],
        activities: ['Adventure Trekking', 'Cliff Photography', 'Echo Testing', 'Cafe Lounging in Vattakanal'],
        openingHours: '06:00 AM – 05:30 PM (Daily)',
        entryFee: 'Free Entry',
        bestPhotoSpot: 'Tip of Dolphin\'s Nose Rock facing Periyakulam valley',
        mapLink: 'https://maps.google.com/?q=Dolphins+Nose+Kodaikanal'
      },
      {
        id: 'mannavanur-lake',
        name: 'Mannavanur Eco Farming Lake & Sheep Farm',
        distance: '34 km from Kodaikanal Town',
        travelTime: '1 hr 15 mins drive',
        image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Known as the "Switzerland of South India", Mannavanur is a serene high-altitude farming village featuring rolling green meadows, a pristine natural lake, coracle boat rides, and the CSWRI Central Sheep Breeding Farm.',
        highlights: ['Rolling green meadow landscape', 'Coracle boat rides on clear lake', 'Central Sheep Breeding Research Farm'],
        activities: ['Coracle Boating', 'Meadow Walking', 'Sheep Petting', 'Countryside Photography'],
        openingHours: '09:00 AM – 05:00 PM (Daily)',
        entryFee: '₹20 Entry (Coracle ₹150)',
        bestPhotoSpot: 'Meadow Hilltop facing the lake with grazing sheep',
        mapLink: 'https://maps.google.com/?q=Mannavanur+Lake'
      },
      {
        id: 'poombarai-village',
        name: 'Poombarai Terraced Garlic Village & Kuzhanthai Velappar Temple',
        distance: '18 km from Kodaikanal Town',
        travelTime: '45 mins drive',
        image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Famous for its 3,000-year-old Kuzhanthai Velappar Murugan Temple consecrated by Sage Bhogar, Poombarai is renowned for its colorful stepped terraced garlic farms cascading down the mountain slopes.',
        highlights: ['3,000-year-old Bhogar Murugan temple', 'Multi-color stepped terraced farms', 'Poombarai organic garlic shopping'],
        activities: ['Temple Darshan', 'Terrace Farm Photography', 'Garlic Shopping', 'Village Strolls'],
        openingHours: '06:00 AM – 08:00 PM (Daily)',
        entryFee: 'Free Entry',
        bestPhotoSpot: 'Poombarai Viewpoint Curve overlooking terraced village',
        mapLink: 'https://maps.google.com/?q=Poombarai+Village'
      }
    ],
    oneDayItinerary: [
      { time: '08:00 AM', title: 'Start & Morning Walk', place: 'Coaker\'s Walk Promenade', desc: 'Enjoy brisk morning air and 180-degree sunrise valley views over Madurai plains.' },
      { time: '09:30 AM', title: 'Attraction 1: Flower Paradise', place: 'Bryant Botanical Park', desc: 'Explore the 740+ rose garden varieties and historic glasshouse.' },
      { time: '11:00 AM', title: 'Attraction 2: Iconic Boating', place: 'Kodaikanal Star Lake', desc: 'Enjoy a relaxing 45-minute pedal boat ride and cycle around the 5 km lake perimeter.' },
      { time: '01:00 PM', title: 'Lunch Break', place: 'Royal Kodai Cuisine', desc: 'Relish authentic South Indian Thali or continental dining in Kodai town center.' },
      { time: '02:00 PM', title: 'Attraction 3: Granite Spires', place: 'Pillar Rocks & Guna Caves', desc: 'Marvel at the 400 ft granite cliff spires and gnarled pine roots from Manjummel Boys fame.' },
      { time: '04:00 PM', title: 'Attraction 4: Movie Canopy', place: 'Dense Pine Tree Forest', desc: 'Walk through century-old towering pine corridors with filtered sunbeams.' },
      { time: '06:00 PM', title: 'Sunset Point', place: 'Green Valley View', desc: 'Watch golden sunset clouds roll over the 5,000 ft deep Vaigai valley.' }
    ]
  },

  'ooty': {
    locationName: 'Ooty (Udhagamandalam)',
    tagline: 'The Queen of Hill Stations & Nilgiri Heritage Railway',
    heroImage: './ooty-toy-train-real.jpg',
    nearestStation: 'Udhagamandalam Railway Station (UAM) / Mettupalayam Junction (MTP) – 51 km',
    nearestAirport: 'Coimbatore International Airport (CJB) – 88 km / Cochin Airport (COK) – 220 km',
    bestTime: 'October to June (Pleasant Summers & Misty Winters)',
    weather: '15°C • Crisp Mountain Mist • Humidity 62%',
    googleMapCoordinates: '11.4102° N, 76.6950° E',
    googleMapLink: 'https://maps.google.com/?q=Ooty',
    attractions: [
      {
        id: 'ooty-toy-train',
        name: 'Nilgiri Mountain Heritage Toy Train (UNESCO World Heritage)',
        distance: '0 km from Ooty Railway Station',
        travelTime: 'Departs from Ooty / Coonoor',
        image: './ooty-toy-train-real.jpg',
        shortDescription: 'Built by the British in 1908, this UNESCO World Heritage rack-and-pinion steam railway winds through 16 tunnels, 250 bridges, and rolling tea estates between Mettupalayam, Coonoor, and Ooty.',
        highlights: ['UNESCO World Heritage vintage steam locomotive', '16 tunnels & 250 scenic gorge bridges', 'Breathtaking Nilgiri mountain panorama'],
        activities: ['Heritage Steam Train Ride', 'Ghat Photography', 'Railway History Tour'],
        openingHours: '09:15 AM, 12:15 PM, 02:00 PM, 04:30 PM (Daily Departures)',
        entryFee: '₹150 First Class / ₹50 Second Class (OASIS VIP Advance Reserved)',
        bestPhotoSpot: 'Viaduct Bridge between Lovedale and Ooty Station',
        mapLink: 'https://maps.google.com/?q=Ooty+Railway+Station'
      },
      {
        id: 'ooty-botanical-gardens',
        name: 'Government Botanical Garden & Italian Glasshouse',
        distance: '2.5 km from Ooty Town Center',
        travelTime: '8 mins drive',
        image: './ooty-botanical-garden-real.jpg',
        shortDescription: 'Established in 1848 by William Graham McIvor, this sprawling 55-acre terraced botanical garden lies on the slopes of Doddabetta Peak. Features a 20-million-year-old fossilized tree trunk, Italian sunken gardens, and over 1,000 exotic floral species.',
        highlights: ['55-acre historic terraced garden', '20-million-year-old fossil tree', 'Ornate Italian sunken floral pavilion'],
        activities: ['Botanical Walking', 'Floral Macro Photography', 'Lawn Picnicking', 'Glasshouse Flora Study'],
        openingHours: '07:00 AM – 06:30 PM (Daily)',
        entryFee: '₹50 Adults, ₹30 Children, ₹100 Camera',
        bestPhotoSpot: 'Central Italian Terrace Lawn framing Doddabetta backdrop',
        mapLink: 'https://maps.google.com/?q=Government+Botanical+Garden+Ooty'
      },
      {
        id: 'ooty-lake-boating',
        name: 'Ooty Lake & Star Boating Jetty',
        distance: '1.0 km from Ooty Bus Stand',
        travelTime: '5 mins drive',
        image: './ooty-lake-boating-real.jpg',
        shortDescription: 'Created in 1824 by John Sullivan, the founder of Ooty, this 65-acre scenic artificial lake is surrounded by lush Eucalyptus trees. Visitors enjoy speedboating, paddle boating, mini-train rides along the banks, and horseback riding.',
        highlights: ['65-acre heritage artificial lake', 'Speedboating & luxury paddle boats', 'Lakeside amusement park & mini train'],
        activities: ['Paddle Boating', 'Speedboating', 'Cycling around Lake Road', 'Horseback Riding'],
        openingHours: '08:30 AM – 06:00 PM (Daily)',
        entryFee: '₹15 Entry (Boating ₹250 – ₹600)',
        bestPhotoSpot: 'Boat House Boardwalk with sunset reflection',
        mapLink: 'https://maps.google.com/?q=Ooty+Lake'
      },
      {
        id: 'ooty-tea-gardens',
        name: 'Nilgiri Tea Plantations & Doddabetta Slopes',
        distance: '4.0 km from Ooty Center',
        travelTime: '12 mins drive',
        image: './ooty-tea-gardens-real.jpg',
        shortDescription: 'Infinite emerald slopes of world-famous Nilgiri orthodox and CTC tea gardens. Tour through live tea processing factories, witness expert tea-plucking, and sample aromatic fresh Nilgiri Orange Pekoe teas.',
        highlights: ['Vast emerald rolling tea carpets', 'Live orthodox tea manufacturing demo', 'Exclusive fresh tea tasting lounge'],
        activities: ['Tea Garden Walks', 'Tea Plucking Experience', 'Orthodox Tea Tasting', 'Landscape Photography'],
        openingHours: '08:00 AM – 06:00 PM (Daily)',
        entryFee: 'Free Entry / Factory Tour ₹20',
        bestPhotoSpot: 'Tea Terrace Curves with Nilgiri blue mountain ridges',
        mapLink: 'https://maps.google.com/?q=Ooty+Tea+Factory'
      },
      {
        id: 'doddabetta-peak',
        name: 'Doddabetta Peak (8,652 ft) & Telescope House',
        distance: '9.0 km from Ooty Town',
        travelTime: '25 mins drive',
        image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'The highest mountain peak in the Nilgiri Hills at 2,637 meters (8,652 feet). Houses an octagonal Telescope House operated by the Tamil Nadu Tourism Development Corporation offering 360-degree views of Chamundi Hills and Coimbatore plains.',
        highlights: ['Highest summit in Nilgiris (8,652 ft)', 'Telescope House observation deck', 'Sweeping 360-degree valley vistas'],
        activities: ['High Altitude Sightseeing', 'Telescope Viewing', 'Forest Canopy Photography', 'Chai & Hot Pakora Stalls'],
        openingHours: '07:00 AM – 06:00 PM (Daily)',
        entryFee: '₹20 Entry, ₹10 Telescope, ₹50 Camera',
        bestPhotoSpot: 'Octagonal Observation Balcony overlooking Coimbatore valley',
        mapLink: 'https://maps.google.com/?q=Doddabetta+Peak'
      },
      {
        id: 'pykara-lake-falls',
        name: 'Pykara Lake, Boating & Cascading Waterfalls',
        distance: '21 km from Ooty Town',
        travelTime: '40 mins drive along Mysore Road',
        image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Sacred to the Toda community, Pykara River originates at Mukurthi Peak and transforms into two breathtaking cascading waterfalls (55m & 61m). Pykara Dam features thrilling speedboat safaris across pristine forest-lined waters.',
        highlights: ['Twin stepped roaring waterfalls', 'High-speed motorboat safari on Pykara Lake', 'Sacred Toda pastoral landscapes'],
        activities: ['Speedboating', 'Waterfall Trail Walks', 'Pine Forest Picnics', 'Nature Photography'],
        openingHours: '09:00 AM – 05:30 PM (Daily)',
        entryFee: '₹10 Entry (Speedboat ₹800/8 persons)',
        bestPhotoSpot: 'Lower Waterfall Viewing Deck & Boating Jetty Pier',
        mapLink: 'https://maps.google.com/?q=Pykara+Waterfalls'
      },
      {
        id: 'avalanche-lake-sanctuary',
        name: 'Avalanche Lake & Trout Hatchery Pine Sanctuary',
        distance: '28 km from Ooty Town',
        travelTime: '55 mins drive',
        image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Formed naturally by an enormous landslide in 1823, Avalanche Lake is nestled in a dense sanctuary of magnolias, orchids, and rhododendrons. Renowned for trout fishing, eco-safari jeep rides, and silent pine forest trails.',
        highlights: ['Untouched pristine mountain lake', 'Trout fishing hatchery & permits', 'Forest Department Eco-Safari bus'],
        activities: ['Eco-Safari Bus Ride', 'Trout Fishing', 'Lakeside Strolls', 'Birdwatching'],
        openingHours: '09:00 AM – 03:00 PM (Safari Timings)',
        entryFee: '₹200 Eco-Safari Bus Pass',
        bestPhotoSpot: 'Lakeside Meadow framing clear blue mountain reflections',
        mapLink: 'https://maps.google.com/?q=Avalanche+Lake+Ooty'
      },
      {
        id: 'ooty-rose-garden',
        name: 'Government Rose Garden (20,000+ Rose Varieties)',
        distance: '3.0 km from Ooty Center',
        travelTime: '10 mins drive',
        image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'India\'s largest rose garden situated on Elk Hill slopes across 10 acres in 5 curved terraces. Houses over 20,000 varieties of roses including hybrid tea roses, miniature roses, floribunda, and rare black/green roses.',
        highlights: ['Largest rose garden in India (10 acres)', 'Over 20,000 rose cultivars', 'Terraced arches & pergola viewpoints'],
        activities: ['Floral Walking', 'Rose Scent Experience', 'Photography', 'Garden Pavilions'],
        openingHours: '08:30 AM – 06:00 PM (Daily)',
        entryFee: '₹40 Adults, ₹20 Children, ₹50 Camera',
        bestPhotoSpot: 'Top Terrace Nila Maadam Pergola overlooking the entire valley of roses',
        mapLink: 'https://maps.google.com/?q=Government+Rose+Garden+Ooty'
      },
      {
        id: 'wenlock-downs-9th-mile',
        name: 'Wenlock Downs (9th Mile Shooting Meadow)',
        distance: '15 km from Ooty on Gudalur Road',
        travelTime: '30 mins drive',
        image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Vast rolling green meadows stretching over 20,000 acres, famed as the backdrop for hundreds of Indian movie songs (Dilwale Dulhania Le Jayenge, Raja Hindustani, Devara). Ideal for horse riding and panoramic walking.',
        highlights: ['20,000 acres of endless rolling green shola downs', 'Famous movie song shooting landmark', 'Highland horse riding'],
        activities: ['Meadow Walks', 'Horse Riding', 'Filming Spot Exploration', 'Sunset Photography'],
        openingHours: '08:00 AM – 06:30 PM (Daily)',
        entryFee: '₹20 Entry',
        bestPhotoSpot: 'Ridge Crest overlooking the 360-degree green rolling shola hills',
        mapLink: 'https://maps.google.com/?q=Wenlock+Downs+9th+Mile'
      },
      {
        id: 'emerald-lake-ooty',
        name: 'Emerald Lake & Silent Tea Valley',
        distance: '25 km from Ooty Town',
        travelTime: '50 mins drive',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Located in the Silent Valley region of the Nilgiris, Emerald Lake is renowned for its tranquil turquoise waters surrounded by terraced tea estates and endemic Nilgiri birds.',
        highlights: ['Turquoise mountain waters & silence', 'Off-beat tranquil escape from tourist crowds', 'Vibrant tea estate backdrop'],
        activities: ['Lakeside Relaxation', 'Birdwatching', 'Tea Plantation Strolls', 'Landscape Art & Photography'],
        openingHours: '08:00 AM – 05:00 PM (Daily)',
        entryFee: 'Free Entry',
        bestPhotoSpot: 'South-western Bank framing tea plantations reflecting in calm water',
        mapLink: 'https://maps.google.com/?q=Emerald+Lake+Ooty'
      },
      {
        id: 'highfield-tea-factory',
        name: 'Highfield Tea Factory & Homemade Chocolate Museum',
        distance: '3.5 km from Coonoor / 18 km from Ooty',
        travelTime: '35 mins drive',
        image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Over 50-year-old operating tea factory showcasing tea leaf drying, rolling, fermentation, and packaging. Features a traditional Nilgiri homemade chocolate making unit and eucalyptus oil distillery.',
        highlights: ['Live aromatic tea & chocolate processing', 'Fresh warm handcrafted chocolates', 'Pure Nilgiri eucalyptus essential oil extraction'],
        activities: ['Factory Tour', 'Chocolate Tasting', 'Spice & Essential Oil Shopping'],
        openingHours: '09:00 AM – 06:30 PM (Daily)',
        entryFee: '₹20 Entry',
        bestPhotoSpot: 'Vintage Copper Roaster & Tea Tasting Room',
        mapLink: 'https://maps.google.com/?q=Highfield+Tea+Factory'
      },
      {
        id: 'mudumalai-tiger-safari',
        name: 'Mudumalai Tiger Reserve & Theppakadu Elephant Camp',
        distance: '40 km from Ooty (via 36 hairpin Ghat bends)',
        travelTime: '1 hr 15 mins drive',
        image: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'One of South India\'s premier wildlife sanctuaries, Mudumalai is home to Bengal tigers, Indian leopards, wild elephants, and gaur. Theppakadu is Asia\'s oldest elephant rehabilitation camp (Oscar winner "The Elephant Whisperers").',
        highlights: ['Oscar-famed Theppakadu Elephant Camp', 'Jungle Jeep & Van Safaris', 'Rich biodiversity of Nilgiri Biosphere Reserve'],
        activities: ['Jungle Safari', 'Elephant Interaction & Feeding Darshan', 'Wildlife Photography'],
        openingHours: '06:00 AM – 10:00 AM & 03:00 PM – 06:00 PM (Safaris)',
        entryFee: 'Safari ₹350 – ₹1,200',
        bestPhotoSpot: 'Moyar River Bank & Theppakadu Elephant Camp Bridge',
        mapLink: 'https://maps.google.com/?q=Mudumalai+Tiger+Reserve'
      }
    ],
    oneDayItinerary: [
      { time: '08:30 AM', title: 'Start & Heritage Ride', place: 'Nilgiri Mountain Toy Train', desc: 'Board the historic UNESCO steam toy train for a mesmerizing ride through pine forests and mountain bridges.' },
      { time: '10:30 AM', title: 'Attraction 1: Terraced Garden', place: 'Government Botanical Garden', desc: 'Stroll through 55 acres of lush lawns, 20-million-year-old fossil tree, and Italian glasshouse.' },
      { time: '12:30 PM', title: 'Attraction 2: Iconic Lake', place: 'Ooty Lake & Boating Pier', desc: 'Enjoy pedal or motor boating and cycle along the scenic perimeter road.' },
      { time: '01:30 PM', title: 'Lunch Break', place: 'Nilgiri Hilltop Restaurant', desc: 'Relish authentic South Indian Thali, piping hot dosas, and fresh homemade Ooty chocolates.' },
      { time: '02:45 PM', title: 'Attraction 3: Highest Summit', place: 'Doddabetta Peak (8,652 ft)', desc: 'Look through telescopes from the summit observation deck for 360-degree valley vistas.' },
      { time: '04:30 PM', title: 'Attraction 4: Tea Experience', place: 'Nilgiri Tea Estates & Factory', desc: 'Walk through rolling emerald tea bushes, watch live tea manufacturing, and sample Orange Pekoe.' },
      { time: '06:00 PM', title: 'Sunset Point', place: 'Wenlock Downs (9th Mile)', desc: 'Watch golden sunset rays wash over endless 20,000-acre green rolling meadows.' }
    ]
  },

  'kashmir': {
    locationName: 'Kashmir Paradise Circuit',
    tagline: 'Dal Lake Shikara, Gulmarg Gondola & Himalayan Valleys',
    heroImage: './kashmir_paradise_ai.png',
    nearestStation: 'Jammu Tawi (JAT) – 260 km / Srinagar Airport (SXR)',
    nearestAirport: 'Sheikh ul-Alam International Airport Srinagar (SXR)',
    bestTime: 'April to October (Flowers) & December to February (Snow)',
    weather: '12°C • Crisp Himalayan Air • Humidity 50%',
    googleMapCoordinates: '34.0837° N, 74.7973° E',
    googleMapLink: 'https://maps.google.com/?q=Srinagar',
    attractions: [
      {
        id: 'dal-lake-shikara',
        name: 'Dal Lake & Royal Shikara Ride',
        distance: '2 km from Srinagar Center',
        travelTime: '5 mins drive',
        image: './dal-lake-shikara-real.jpg',
        shortDescription: 'Mirror-still waters of Dal Lake flanked by majestic Zabarwan mountain ranges with traditional decorated Shikara boats.',
        highlights: ['Shikara sunset ride', 'Floating market & lotus garden', 'Houseboat luxury stay'],
        activities: ['Shikara Cruise', 'Houseboat Dining', 'Kahwa Tea Tasting'],
        openingHours: '06:00 AM – 09:00 PM (Daily)',
        entryFee: 'Shikara ₹600 – ₹1,200/hr',
        bestPhotoSpot: 'Boulevard Road Shikara Ghat No. 7 at sunset',
        mapLink: 'https://maps.google.com/?q=Dal+Lake+Srinagar'
      },
      {
        id: 'gulmarg-gondola',
        name: 'Gulmarg Gondola & Apharwat Peak',
        distance: '50 km from Srinagar',
        travelTime: '1 hr 30 mins drive',
        image: './gulmarg-real.jpg',
        shortDescription: 'World\'s second-highest operating cable car reaching 13,780 ft on Mount Apharwat with breathtaking snow bowls.',
        highlights: ['Phase 1 & Phase 2 Gondola ride', 'Snow skiing & sledging', 'St. Mary\'s Church & golf course'],
        activities: ['Gondola Cable Car Ride', 'Snow Sledging', 'High Altitude Photography'],
        openingHours: '09:00 AM – 05:00 PM (Daily)',
        entryFee: 'Gondola Phase 1 ₹800, Phase 2 ₹1,000',
        bestPhotoSpot: 'Kongdoori Phase 2 Station overlooking Pir Panjal peaks',
        mapLink: 'https://maps.google.com/?q=Gulmarg+Gondola'
      }
    ],
    oneDayItinerary: [
      { time: '08:00 AM', title: 'Morning Shikara', place: 'Dal Lake Srinagar', desc: 'Private Shikara ride through floating vegetable markets and lotus channels.' },
      { time: '10:30 AM', title: 'Mughal Splendor', place: 'Shalimar & Nishat Bagh', desc: 'Explore 17th-century terraced Mughal gardens with cascading fountains.' },
      { time: '02:00 PM', title: 'Himalayan Ridge', place: 'Gulmarg Gondola', desc: 'Ascend to Kongdoori & Apharwat snow meadows.' },
      { time: '06:00 PM', title: 'Twilight Houseboat', place: 'Dal Lake Heritage Suite', desc: 'Traditional Kashmiri Wazwan dinner with fresh Kahwa tea.' }
    ]
  },

  'kashi': {
    locationName: 'Kashi, Ayodhya & Prayagraj',
    tagline: 'Sacred Northern Pilgrimage Yatra from Thrissur',
    heroImage: './kashi-vishwanath-real.jpg',
    nearestStation: 'Varanasi Junction (BSB) / Ayodhya Dham (AY)',
    nearestAirport: 'Lal Bahadur Shastri Airport Varanasi (VNS)',
    bestTime: 'October to March',
    weather: '22°C • Clear & Serene • Humidity 45%',
    googleMapCoordinates: '25.3176° N, 82.9739° E',
    googleMapLink: 'https://maps.google.com/?q=Varanasi',
    attractions: [
      {
        id: 'kashi-vishwanath-corridor',
        name: 'Kashi Vishwanath Jyotirlinga & Golden Temple',
        distance: '4 km from Varanasi Cantt Station',
        travelTime: '15 mins drive',
        image: './kashi-vishwanath-real.jpg',
        shortDescription: 'One of the 12 sacred Jyotirlingas of Lord Shiva on the western bank of holy Ganga.',
        highlights: ['VIP Darshan & Abhishek', 'Grand riverfront corridor', 'Ancient Gyanvapi site'],
        activities: ['Temple Darshan', 'Riverfront Walk', 'Sanskrit Chanting'],
        openingHours: '03:00 AM – 11:00 PM (Daily)',
        entryFee: 'Free Darshan / VIP Pass Available',
        bestPhotoSpot: 'Ganga Viewpoint Corridor Gate',
        mapLink: 'https://maps.google.com/?q=Kashi+Vishwanath+Temple'
      },
      {
        id: 'ayodhya-ram-mandir-spot',
        name: 'Shri Ram Janmabhoomi Mandir Ayodhya',
        distance: '140 km from Varanasi',
        travelTime: '2 hrs 45 mins express drive',
        image: './ayodhya-ram-mandir-real.jpg',
        shortDescription: 'Grand pink sandstone Nagara-style temple consecrated to Bhagwan Shri Ram.',
        highlights: ['Shri Ram Lalla VIP Darshan', 'Saryu River Maha Aarti', 'Hanuman Garhi Temple'],
        activities: ['Darshan', 'Saryu Holy Dip', 'Evening Aarti'],
        openingHours: '06:30 AM – 09:30 PM (Daily)',
        entryFee: 'Free Entry / VIP Slot Reserved',
        bestPhotoSpot: 'Ram Mandir Front Concourse at twilight lighting',
        mapLink: 'https://maps.google.com/?q=Shri+Ram+Janmabhoomi+Ayodhya'
      }
    ],
    oneDayItinerary: [
      { time: '05:30 AM', title: 'Sunrise Boat Cruise', place: 'Assi to Dashashwamedh Ghat', desc: 'Witness ancient Vedic morning rituals and sunrise over holy Ganga.' },
      { time: '08:30 AM', title: 'Kashi Darshan', place: 'Kashi Vishwanath Corridor', desc: 'VIP Abhishek and Darshan at Jyotirlinga sanctum.' },
      { time: '01:00 PM', title: 'Sattvic Lunch', place: 'Kashi Thali', desc: 'Authentic Banarasi Kachori, Sabzi, Malaiyyo & Lassi.' },
      { time: '05:30 PM', title: 'Grand Aarti', place: 'Dashashwamedh Ghat', desc: 'Exclusive VIP boat seating for synchronized twilight brass lamp Aarti.' }
    ]
  },
  'nepal': {
    locationName: 'Nepal (Himalayan Kingdom & Kathmandu Valley)',
    tagline: 'Roof of the World, Sacred Pashupatinath & Annapurna Lakes',
    heroImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1920&q=85',
    nearestStation: 'Raxaul Junction (India-Nepal Border) / Direct Flight to KTM',
    nearestAirport: 'Tribhuvan International Airport (KTM) – Kathmandu / Pokhara Int Airport (PKR)',
    bestTime: 'September to May (Crisp Himalayan Sunrise & Clear Peak Vistas)',
    weather: '19°C • Pleasant Mountain Air • Humidity 55%',
    googleMapCoordinates: '27.7172° N, 85.3240° E',
    googleMapLink: 'https://maps.google.com/?q=Kathmandu+Nepal',
    attractions: [
      {
        id: 'nepal-pashupatinath',
        name: 'Pashupatinath Sacred Shiva Temple & Bagmati Ghats',
        distance: '4.5 km from Kathmandu Center',
        travelTime: '15 mins drive',
        image: 'https://images.unsplash.com/photo-1582650625119-3a31f8418b7d?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'One of the holiest Hindu temples in the world dedicated to Lord Shiva, located on the sacred Bagmati River. Features cubic pagoda architecture, silver-sheeted doors, and evening sandhya Maha Aarti.',
        highlights: ['UNESCO World Heritage 5th-century shrine', 'Sacred Bagmati River twilight Maha Aarti', 'Golden spire pagoda architecture & VIP Darshan'],
        activities: ['Spiritual Darshan', 'Bagmati Aarti Witnessing', 'Heritage Photography', 'Sacred Rituals'],
        openingHours: '04:00 AM – 09:00 PM (Daily)',
        entryFee: 'Free for Indian/Nepalese Nationals (VIP Pass Arranged by OASIS)',
        bestPhotoSpot: 'Eastern bank terraces facing the central pagoda and Bagmati ghats',
        mapLink: 'https://maps.google.com/?q=Pashupatinath+Temple+Kathmandu'
      },
      {
        id: 'nepal-phewa-lake',
        name: 'Pokhara Phewa Lake & Tal Barahi Island Temple',
        distance: '2 km from Pokhara Lakeside',
        travelTime: '5 mins drive / Walk',
        image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'The second largest lake in Nepal, Phewa Lake mirrors the snowy peaks of Mount Machapuchare (Fishtail) and the Annapurna mountain range. Features colorful wooden boat rides to the island temple of Tal Barahi.',
        highlights: ['Mirror reflection of Mt. Machapuchare & Annapurna', 'Tal Barahi two-story pagoda island temple', 'Sunset lakeside cafes and mountain walks'],
        activities: ['Traditional Wooden Boating', 'Island Temple Visit', 'Mountain Reflection Photography', 'Lakeside Strolls'],
        openingHours: '06:00 AM – 06:30 PM (Daily)',
        entryFee: 'Boat Ride ₹300 – ₹500',
        bestPhotoSpot: 'South-west lakeside bank during calm morning sunrise with mountain reflection',
        mapLink: 'https://maps.google.com/?q=Phewa+Lake+Pokhara'
      },
      {
        id: 'nepal-sarangkot',
        name: 'Sarangkot Annapurna & Dhaulagiri Sunrise Viewpoint',
        distance: '11 km from Pokhara Lakeside',
        travelTime: '25 mins uphill drive',
        image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Perched at 1,600m above sea level, Sarangkot offers a panoramic 180-degree view of the Annapurna mountain range (Annapurna I, II, Machapuchare, and Dhaulagiri) turning from purple to fiery gold at dawn.',
        highlights: ['World-renowned 360° Himalayan sunrise', 'Unobstructed vistas of 8,000m+ Himalayan summits', 'Pokhara Valley & Phewa Lake aerial perspective'],
        activities: ['Himalayan Sunrise Excursion', 'Panoramic Photography', 'Telescope Peak Gazing'],
        openingHours: '04:30 AM – 07:00 PM (Best at 05:30 AM Sunrise)',
        entryFee: '₹100 Entry',
        bestPhotoSpot: 'Upper Viewpoint Tower facing Annapurna massif at first light',
        mapLink: 'https://maps.google.com/?q=Sarangkot+Pokhara'
      },
      {
        id: 'nepal-boudhanath',
        name: 'Boudhanath Stupa (Ancient Tibetan Mandala)',
        distance: '6 km from Kathmandu Center',
        travelTime: '20 mins drive',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'One of the largest spherical stupas in the world and center of Tibetan Buddhism in Nepal. Surrounded by monastery rooftops, prayer flags fluttering in mountain breeze, and aromatic Tibetan incense shops.',
        highlights: ['Massive 36-meter high spherical Buddhist mandala', '108 prayer wheels for clockwise circumambulation', 'Rooftop cafes with panoramic stupa views'],
        activities: ['Kora (Circumambulation)', 'Monastery Visit', 'Tibetan Singing Bowls & Thangka Art', 'Sunset Viewing'],
        openingHours: '24 Hours Open (Monasteries 06:00 AM – 06:00 PM)',
        entryFee: '₹100 Entry',
        bestPhotoSpot: '3rd-floor rooftop cafe facing the Buddha eyes at golden hour',
        mapLink: 'https://maps.google.com/?q=Boudhanath+Stupa+Kathmandu'
      },
      {
        id: 'nepal-swayambhunath',
        name: 'Swayambhunath Monkey Temple Stupa',
        distance: '3 km west of Kathmandu',
        travelTime: '12 mins drive',
        image: 'https://images.unsplash.com/photo-1582650625119-3a31f8418b7d?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Crowning a hilltop overlooking Kathmandu Valley, this 5th-century UNESCO World Heritage site features a gleaming white dome, gilded spire, the all-seeing eyes of Buddha, and ancient stone stupas.',
        highlights: ['365 stone steps pilgrimage climb', 'Panoramic 360° view of entire Kathmandu Valley', 'Centuries-old stone chaityas & holy monkeys'],
        activities: ['Hilltop Walk', 'Valley View Watching', 'Temple Blessings', 'Photography'],
        openingHours: '24 Hours Open (Best for Morning & Sunset)',
        entryFee: '₹100 Entry',
        bestPhotoSpot: 'Eastern Stairway Platform overlooking Kathmandu skyline',
        mapLink: 'https://maps.google.com/?q=Swayambhunath+Kathmandu'
      },
      {
        id: 'nepal-chitwan',
        name: 'Chitwan National Park Tiger & Rhino Sanctuary',
        distance: '150 km south-west of Kathmandu',
        travelTime: 'Escorted AC Tourist Coach',
        image: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'Nepal\'s first UNESCO World Heritage National Park protecting the lush subtropical inner Terai lowlands. Famous for open jeep safaris spotting the Great One-Horned Rhinoceros, Bengal Tiger, Gharials, and 500+ bird species.',
        highlights: ['Close encounters with Greater One-Horned Rhinos', 'Jeep & Canoe river safaris along Rapti River', 'Traditional Tharu cultural dance & village tour'],
        activities: ['Jungle Jeep Safari', 'Rapti River Canoe Ride', 'Bird Watching', 'Tharu Cultural Show'],
        openingHours: '06:00 AM – 06:00 PM (Daily)',
        entryFee: 'Park Permit Included in OASIS Package',
        bestPhotoSpot: 'Rapti River bank at sunset with elephants in silhouette',
        mapLink: 'https://maps.google.com/?q=Chitwan+National+Park+Sauraha'
      },
      {
        id: 'nepal-bhaktapur',
        name: 'Bhaktapur Durbar Square & 55-Window Palace',
        distance: '13 km east of Kathmandu',
        travelTime: '30 mins drive',
        image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'A living museum of medieval Newari art and architecture dating from the Malla Kingdom. Highlights include the 55-Window Palace, Golden Gate, and the towering 30-meter high Nyatapola 5-story pagoda temple.',
        highlights: ['Nyatapola Temple — Highest pagoda in Nepal (1702)', '55-Window Royal Palace & Golden Gate (Sun Dhoka)', 'Pottery Square with traditional artisan wheel craft'],
        activities: ['Heritage Architecture Walk', 'Pottery Making Observation', 'King Curd (Juju Dhau) Tasting'],
        openingHours: '07:00 AM – 07:00 PM (Daily)',
        entryFee: '₹100 for SAARC Citizens',
        bestPhotoSpot: 'Nyatapola Temple stone staircase looking over the square',
        mapLink: 'https://maps.google.com/?q=Bhaktapur+Durbar+Square'
      },
      {
        id: 'nepal-nagarkot',
        name: 'Nagarkot Himalayan Panoramic & Everest View Ridge',
        distance: '32 km east of Kathmandu (Altitude 2,175m)',
        travelTime: '1 hr drive',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        shortDescription: 'High-altitude ridge on the northeastern rim of Kathmandu Valley. Famous for world-class panoramic views of 8 Himalayan mountain ranges, including sunrise vistas of Mount Everest on clear horizon days.',
        highlights: ['Panoramic view of 8 out of 14 world\'s highest ranges', 'Crisp pine forest mountain walks & fresh air', 'Breathtaking sunrise over eastern Himalayan summits'],
        activities: ['Sunrise View Excursion', 'Pine Trail Hiking', 'Mountain Panorama Photography'],
        openingHours: '24 Hours Open (Best at 05:15 AM Sunrise)',
        entryFee: 'Free Entry',
        bestPhotoSpot: 'Nagarkot View Tower at dawn facing Mount Everest ridge',
        mapLink: 'https://maps.google.com/?q=Nagarkot+View+Tower'
      }
    ],
    oneDayItinerary: [
      { time: '05:30 AM', title: 'Sarangkot Sunrise', place: 'Sarangkot Ridge Pokhara', desc: 'Behold the golden sun illuminate Annapurna I and Machapuchare peaks.' },
      { time: '08:30 AM', title: 'Pashupatinath VIP Darshan', place: 'Pashupatinath Temple', desc: 'Special Vedic darshan at the holy Shiva sanctum on the banks of Bagmati.' },
      { time: '11:00 AM', title: 'Boudhanath Tibetan Mandala', place: 'Boudhanath Stupa', desc: 'Circumambulate with prayer wheels and explore Tibetan monastery art.' },
      { time: '01:00 PM', title: 'Authentic Himalayan Lunch', place: 'Lakeside / Heritage Dining', desc: 'Enjoy authentic Nepalese Dal Bhat Thali, Momos & multi-cuisine lunch.' },
      { time: '03:30 PM', title: 'Swayambhunath Monkey Temple', place: 'Swayambhunath Hill', desc: 'Admire ancient 5th-century stupas and 360-degree Kathmandu Valley views.' },
      { time: '05:30 PM', title: 'Phewa Lake Boating & Tal Barahi', place: 'Phewa Lake Pokhara', desc: 'Scenic private wooden boat cruise to island shrine with mountain reflections.' },
      { time: '07:00 PM', title: 'Pashupatinath Bagmati Maha Aarti', place: 'Bagmati River Ghats', desc: 'Witness grand synchronized brass lamp twilight Maha Aarti with Vedic chanting.' }
    ]
  },
  'kathmandu': null,
  'pokhara': null,
  'chitwan': null
};

// Aliases for Nepal
AI_DESTINATION_DATABASE['kathmandu'] = AI_DESTINATION_DATABASE['nepal'];
AI_DESTINATION_DATABASE['pokhara'] = AI_DESTINATION_DATABASE['nepal'];
AI_DESTINATION_DATABASE['chitwan'] = AI_DESTINATION_DATABASE['nepal'];

/**
 * Universal AI Destination Guide Generator Function
 * Accepts any location name string and returns a complete prompt-compliant destination guide object.
 */
export function generateAiDestinationGuide(locationInput = 'Kodaikanal') {
  const normalizedKey = (locationInput || '').trim().toLowerCase();
  
  if (AI_DESTINATION_DATABASE[normalizedKey]) {
    return AI_DESTINATION_DATABASE[normalizedKey];
  }

  // Check substring matches
  if (normalizedKey.includes('nepal') || normalizedKey.includes('kathmandu') || normalizedKey.includes('pokhara') || normalizedKey.includes('chitwan') || normalizedKey.includes('everest') || normalizedKey.includes('pashupatinath')) {
    return AI_DESTINATION_DATABASE['nepal'];
  }


  // Dynamic Generator Fallback for any location
  const locName = locationInput.trim() || 'Kodaikanal';
  return {
    locationName: locName,
    tagline: `Premier Tourist Destination Guide for ${locName}`,
    heroImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1920&q=85',
    nearestStation: `${locName} Railway Junction – 15 km`,
    nearestAirport: `Regional International Airport – 65 km`,
    bestTime: 'October to May (Peak Season)',
    weather: '22°C • Pleasant & Refreshing • Humidity 60%',
    googleMapCoordinates: '10.0000° N, 77.0000° E',
    googleMapLink: `https://maps.google.com/?q=${encodeURIComponent(locName)}`,
    attractions: [
      {
        id: `${normalizedKey}-1`,
        name: `${locName} Central Lake & Promenade`,
        distance: '1.5 km from Town Center',
        travelTime: '5 mins drive',
        image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        shortDescription: `A scenic natural lake surrounded by mountain slopes in ${locName}. Popular for morning walks, pedal boating, perimeter cycling, and local street snacks.`,
        highlights: ['Scenic waterfront promenade', 'Pedal boating', 'Mountain views'],
        activities: ['Boating', 'Walking', 'Photography', 'Snacking'],
        openingHours: '06:00 AM – 06:00 PM (Daily)',
        entryFee: 'Free Entry (Boating ₹200)',
        bestPhotoSpot: 'Lake Pier at sunrise',
        mapLink: `https://maps.google.com/?q=${encodeURIComponent(locName + ' Lake')}`
      },
      {
        id: `${normalizedKey}-2`,
        name: `${locName} Peak Viewpoint`,
        distance: '6.0 km from Town Center',
        travelTime: '15 mins drive',
        image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
        shortDescription: `Highest elevation lookout point near ${locName} offering 360-degree views of valley forests, mountain ridges, and cloud beds.`,
        highlights: ['360-degree panoramic vista', 'Cloudbed sunset views', 'Telescope lookout'],
        activities: ['Sightseeing', 'Trekking', 'Sunset Watching'],
        openingHours: '07:00 AM – 06:30 PM (Daily)',
        entryFee: '₹20 Entry',
        bestPhotoSpot: 'Top Observation Deck',
        mapLink: `https://maps.google.com/?q=${encodeURIComponent(locName + ' Viewpoint')}`
      },
      {
        id: `${normalizedKey}-3`,
        name: `${locName} Botanical Rose Gardens`,
        distance: '3.0 km from Town Center',
        travelTime: '10 mins drive',
        image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1200&q=80',
        shortDescription: `Landscaped botanical gardens in ${locName} featuring over 500 flower species, glasshouses, manicured lawns, and shaded walking paths.`,
        highlights: ['500+ flower species', 'Glasshouse flora', 'Lawn picnic area'],
        activities: ['Botanical Walks', 'Photography', 'Relaxation'],
        openingHours: '08:30 AM – 06:00 PM (Daily)',
        entryFee: '₹30 Adults',
        bestPhotoSpot: 'Glasshouse Entrance Lawn',
        mapLink: `https://maps.google.com/?q=${encodeURIComponent(locName + ' Botanical Garden')}`
      }
    ],
    oneDayItinerary: [
      { time: '08:00 AM', title: 'Start & Morning Walk', place: `${locName} Promenade`, desc: 'Enjoy fresh mountain air and morning valley views.' },
      { time: '09:30 AM', title: 'Attraction 1: Botanical Garden', place: `${locName} Rose Gardens`, desc: 'Explore floral glasshouses and manicured lawns.' },
      { time: '11:00 AM', title: 'Attraction 2: Lake Boating', place: `${locName} Central Lake`, desc: 'Enjoy pedal boating and lake cycling.' },
      { time: '01:00 PM', title: 'Lunch Break', place: `${locName} Town Dining`, desc: 'Enjoy authentic regional cuisine.' },
      { time: '02:30 PM', title: 'Attraction 3: Mountain Peak', place: `${locName} Peak Viewpoint`, desc: 'Experience 360-degree valley vistas.' },
      { time: '06:00 PM', title: 'Sunset Point', place: `${locName} Sunset Cliff`, desc: 'Watch golden sunset over mountain ridges.' }
    ]
  };
}
